Improve Django Admin integration with original package
saritasa-nest/django-import-export-extensions pull request #11
Opened 2023-08-25 04:25 UTC by NikAzanov

Prior to this, all admin models and admin templates were rewritten from the original package and didn't use inheritance. In this PR I tried to reuse the `django-import-export` code by inheritance to reduce the amount of code and make it easier to make changes.

In this PR:
* Improve GitHub workflow name
* Get rid of `DjangoObjectActions` and implement default django admin action instead (Maybe later we can extend this)
* Use `mixins.BaseExportMixin`, `mixins.BaseImportMixin` and `admin.ImportExportMixinBase` from original package for celery admin mixins
* Use `admin/import_export/` templates instead of copies in `admin/import_export_ext/`
* Small improvements:
	* Fix static folder name
	* Fix invoke command to run celery
	* Fix progress bar widget
	* Rename `filter_class` to `filterset_class`
	* Add `cancel_job` action for exporting

2023-09-01 06:45 UTC, ron8mcr requested changes

2023-09-01 06:45 UTC, ron8mcr commented on .github/workflows/checks.yml
> +name: Django-import-export-extensions CI
Let's find better name, actually this actions perform checks, and `CI` is too common name

2023-09-01 06:45 UTC, ron8mcr commented on import_export_extensions/admin/mixins/export_mixin.py
> +    export_results_template_name = "admin/import_export_ext/celery_export_results.html"
Let's use full name "import_export_extensions", just like in `INSTALLED_APPS`

2023-09-01 06:45 UTC, ron8mcr commented on import_export_extensions/admin/model_admins/export_job_admin.py
> +                    _("Export Canceled"),
Let's also add representation of failed `obj` to messages, ex:
"Export of {str(obj)} Canceled"

2023-09-01 06:45 UTC, ron8mcr commented on import_export_extensions/models/export_job.py
> +        status_task_field_map = {
Do you really need this map?

2023-09-08 10:11 UTC, yalef commented on import_export_extensions/admin/mixins/import_mixin.py
> +    def has_import_permission(self, request):
Let's add typing for `request`

2023-09-08 10:11 UTC, yalef commented on import_export_extensions/admin/model_admins/export_job_admin.py
> +    actions = [
can we use tuple here?

2023-09-08 10:11 UTC, yalef commented on import_export_extensions/admin/model_admins/export_job_admin.py
> +    def cancel_jobs(self, request, queryset):
let's add typings

2023-09-08 10:11 UTC, yalef commented on import_export_extensions/admin/model_admins/import_job_admin.py
> +    actions = [
can we use tuple here?

2023-09-08 10:11 UTC, yalef commented on import_export_extensions/admin/model_admins/import_job_admin.py
> +    def cancel_jobs(self, request, queryset):
Let's add typings here too

2023-09-08 10:11 UTC, yalef commented on README.rst
> +Add `import_export` and `import_export_extensions` to INSTALLED_APPS
As I mention in other PR's I think we should use  double quotes instead of single ones

2023-09-11 06:17 UTC, merged