Update dependencies
saritasa-nest/django-import-export-extensions pull request #36
Opened 2024-09-05 09:39 UTC by Eg0ra

2024-09-05 10:21 UTC, TheSuperiorStanislav requested changes
Let's add dependabot, checkout out boilerplate

2024-09-06 02:45 UTC, TheSuperiorStanislav approved these changes

2024-09-06 05:43 UTC, OttoAndrey approved these changes

2024-09-06 09:33 UTC, NikAzanov approved these changes

2024-09-06 09:34 UTC, merged