Add tests for export job admin progress
saritasa-nest/django-import-export-extensions pull request #56
Opened 2024-10-18 09:56 UTC by Eg0ra

2024-10-21 03:35 UTC, NikAzanov requested changes

2024-10-21 03:35 UTC, NikAzanov commented on import_export_extensions/models/export_job.py
> -        Example for sync mode::
Let's also update part about "celery (celery) mode". I guess now it's relevant for any mode, so just remove `celery` mentions.

Also I see "Possible states" in docstring, but can we also add this enum to `TaskStateInfo`?

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/integration_tests/test_admin/test_export.py
> +def test_export_progress_for_sync_mode(
Is there a difference between sync/async modes now?

Please, provide more detailed docstring (why there are two different tests for sync and async and how it works)

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/integration_tests/test_admin/test_export.py
> +    expected_percent = 66
```suggestion
    fake_progress_info = {
        "current": 2,
        "total": 3,
    }
    mocker.patch(
        "celery.result.AsyncResult.info",
        new=fake_progress_info,
    )
    expected_percent = int(fake_progress_info["current"] / fake_progress_info["total"])
```

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/integration_tests/test_admin/test_export.py
> +    assert response.json()["percent"] == expected_percent
Why `response.json()` again?

Maybe prepare an object like `{"percent": expected_percent, **fake_progress_info}` and compare with it?

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/integration_tests/test_admin/test_export.py
> +    assert response.json()["validation_error"] == expected_error_message
![image](https://github.com/user-attachments/assets/3fa38f5f-a39b-441c-86f9-32a681f9c1cd)

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/integration_tests/test_admin/test_export.py
> +        new="Mocked Error Message",
Can `AsyncResult.info` be a string? 

I guess we'll need to improve typing (`TaskStateInfo`)

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/integration_tests/test_admin/test_export.py
> +    """Test export job admin progress page with deleted export job."""
Please improve docstring with the purpose of test (check than after celery fail there will be export error)

2024-10-21 03:35 UTC, NikAzanov commented on test_project/tests/test_import_job/test_import_data.py
> +    )
I'm not sure that hardcoding value is a good practice. Maybe just check `f"Too many rows `2`" in import_job.error_message`? Or the best way is to move error message in a constance and then just reuse in tests

2024-10-21 11:39 UTC, OttoAndrey approved these changes

2024-10-21 13:23 UTC, NikAzanov approved these changes

2024-10-22 01:39 UTC, NikAzanov approved these changes

2024-10-22 02:15 UTC, TheSuperiorStanislav approved these changes

2024-10-22 02:15 UTC, TheSuperiorStanislav commented on import_export_extensions/admin/model_admins/export_job_admin.py
> +from http import HTTPStatus
```suggestion
import http

http.HTTPStatus.NOT_FOUND
```
Just personal preference

2024-10-24 07:09 UTC, merged