Add support for multiple resource classes
saritasa-nest/django-import-export-extensions pull request #7
Opened 2023-06-07 06:32 UTC by KhoiCaoSaritasa

- add support for multiple resource classes
- refactor `CeleryExportAdminMixin`, `CeleryImportAdminMixin`: 
    - move common logic to a base class
    - drop `get_export_formats`, `get_import_formats`: we now support multiple resource classes, and each resource supports different set of formats, so those formats should be retrieved by calling the corresponding methods on resource class

2023-07-11 04:27 UTC, NikAzanov requested changes
So let's get rid of deprecated `resource_class` logic. It already deprecated in original package, but we have a chance just remove it because our package wasn't released yet.

2023-07-11 04:27 UTC, NikAzanov commented on import_export_extensions/admin/mixins/base.py
> +        self, request, *args, **kwargs,
Put each argument on the new line
```suggestion
        self,
        request,
        *args,
        **kwargs,
```

2023-07-11 04:27 UTC, NikAzanov commented on import_export_extensions/admin/mixins/base.py
> +    def get_resource_index(self, form) -> int:
Would be nice to add type hint to `form` argument

2023-07-11 04:27 UTC, NikAzanov commented on import_export_extensions/admin/mixins/base.py
> +    def get_import_resource_classes(self) -> typing.Sequence[ResourceType]:
> "be conservative in what you send, be liberal in what you accept" - Postel's law (robustness principle)

```suggestion
    def get_import_resource_classes(self) -> list[ResourceType]:
```

2023-07-11 04:27 UTC, NikAzanov commented on import_export_extensions/static/import_export_extensions/js/admin/export_form.js
> +    const exportForm = $('#export-form');
Please, unify quotes, use `"`

2023-08-09 10:33 UTC, OttoAndrey commented on tests/settings.py
> +    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
```suggestion
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
```

2024-10-07 04:26 UTC, closed without merging